name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # запускать каждый день в полночь
  workflow_dispatch: # позволяет запускать вручную

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: sad-jack
          output: dist/github-contribution-grid-snake.svg

      - name: Push the generated Snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true