name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Запуск ежедневно
  workflow_dispatch: # Ручной запуск
  push:
    branches:
      - master # Запуск при пуше в master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Sad-Jack # Ваш никнейм

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # Папка, содержащая сгенерированные SVG
          target_branch: gh-pages  # Публикуем на ветку gh-pages