name: Generate and Deploy Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск ежедневно
  workflow_dispatch:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Права на запись в репозиторий

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Sad-Jack

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ github.run_id }}  # Уникальное имя артефакта
          path: dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages  # Правильный параметр